### ISSUE TITLE
Package is unnecessary when using Symfony 3.3+

### ISSUE THREAD

**Issue by stof** [endroid/Asset#1]
Symfony 3.3 already supports reading JSON manifests when using the `asset` function (and keeps the manifest path in the bundle config rather than forcing to give it for each usage in the templates, which is nicer).

So I suggest recommending to use the Symfony built-in support rather than this bundle for Symfony 3.3+ (I have no idea what your Symfony supported versions are, as you don't have any composer rules about that, meaning that you could install it with any Symfony version)

**Comment by endroid** [comment]
Hi @stof I created the library because I could not find a way to work with multiple manifest files at the same time. I.e. when my application has a manifest I can configure using framework.assets.json_manifest_path, but when I install a bundle that has its own manifest I am not able to distinguish between the both. How would you handle such a case?

That is the only reason I created the library so if there is another way that is already supported I am happy to adapt :)

**Comment by stof** [comment]
@endroid Symfony supports having multiple asset packages, with their own versionning each: http://symfony.com/doc/current/reference/configuration/framework.html#packages

And then, when using the `asset()` function, you can pass the package name as second argument when you want to use a different package than the default one.

**Comment by endroid** [comment]
@stof I did not know that was possible :) I now created a prepend method in my bundle that automatically adds the bundle to the packages upon installation and will now remove my Asset library and reference in recipes-contrib as I think it is no longer needed.
